name: Code Warden Release Tagging

on:
  release:
    types:
      - created

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Latest Release
        id: get-latest-release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const releases = response.data.filter(release => !release.draft && !release.prerelease);
            const latestReleaseTag = releases[0]?.tag_name || "0.0.0";
            return latestReleaseTag
          
  

      - name: Get Latest Release Tag Version
        id: get-latest-release-tag
        run: |
          latestTag=${{ steps.get-latest-release.outputs.result }}
          if [[ $latestTag =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            latestMajorVersion="${major}"
            latestReleasedVersion="${major}.${minor}.${patch}"
            latestReleasedTagVersionWithBuild="${latestTag}"
          fi
       
          echo "latestReleasedTagVersionWithBuild=${latestReleasedTagVersionWithBuild}"
          echo "latestReleasedTagMajorVersion=${latestMajorVersion}"
          echo "latestReleasedVersion=${latestReleasedVersion}"
          
          echo "latestReleasedTagVersionWithBuild=$latestReleasedTagVersionWithBuild" >> $GITHUB_OUTPUT
          echo "latestReleasedTagMajorVersion=$latestMajorVersion" >> $GITHUB_OUTPUT
          echo "latestReleasedVersion=$latestReleasedVersion" >> $GITHUB_OUTPUT

      - name: Create release tags
        id: create-release-tag
        run: |
            tagMajorVersion="v${{ steps.get-latest-release-tag.outputs.latestReleasedTagMajorVersion }}"
            latestReleasedVersion="v${{ steps.get-latest-release-tag.outputs.latestReleasedVersion }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"

            if git show-ref --tags --quiet --verify -- "refs/tags/${tagMajorVersion}"; then
              echo "Tag '${tagMajorVersion}' already exists. Deleting the existing tag to recreate"
              git tag -d "${tagMajorVersion}"
              git push --delete origin "${tagMajorVersion}"
            fi

            if git show-ref --tags --quiet --verify -- "refs/tags/${latestReleasedVersion}"; then
              echo "Tag '${latestReleasedVersion}' already exists. Deleting the existing tag to recreate"
              git tag -d "${latestReleasedVersion}"
              git push --delete origin "${latestReleasedVersion}"
            fi

            echo "Creating tag ${tagMajorVersion} from ${latestReleasedTagVersionWithBuild}"
            git tag ${tagMajorVersion} ${latestReleasedTagVersionWithBuild}
            git push origin ${tagMajorVersion}

            echo "Creating tag ${latestReleasedVersion} from ${latestReleasedTagVersionWithBuild}"
            git tag ${latestReleasedVersion} ${latestReleasedTagVersionWithBuild}
            git push origin ${latestReleasedVersion}

